---
abstract: 'Premake5 build plugin for Alien::Build'
author:
  - 'José Joaquín Atria <jjatria@cpan.org>'
build_requires:
  Alien::Build::Plugin::Build::Premake: '0'
  Path::Tiny: '0'
  Test2::V0: '0'
  Test::Alien::Build: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-Build-Plugin-Build-Premake5
provides:
  Alien::Build::Plugin::Build::Premake5:
    file: lib/Alien/Build/Plugin/Build/Premake5.pm
    version: '0.001'
requires:
  Alien::Build::Plugin: '0'
  Alien::premake5: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/jjatria/Alien-Build-Plugin-Build-Premake5/issues
  repository: git://github.com/jjatria/Alien-Build-Plugin-Build-Premake5.git
version: '0.001'
x_serialization_backend: 'YAML::Tiny version 1.70'
